# Generated by Django 2.1.15 on 2020-09-13 12:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeditoCliente',
            new_name='PedidoCliente',
        ),
    ]
