# Generated by Django 2.1.15 on 2020-09-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20200913_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidocliente',
            old_name='cliente',
            new_name='user',
        ),
    ]
