# Generated by Django 2.1.15 on 2020-09-13 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20200913_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocliente',
            name='produtos',
            field=models.ManyToManyField(related_name='produtos', through='loja.PedidoProduto', to='loja.Produto'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='pedido_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='loja.PedidoCliente'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='loja.Produto'),
        ),
    ]
